/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kaiserdj.chat.client;

import Objetos.Usuario;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import metodos.Serverchat;
import metodos.Utilidades;
import otros.Variables;

/**
 *
 * @author gonfe
 */
public class Main_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Main_Admin
     */
    public Main_Admin() {
        initComponents();
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialog_RegistrarUser = new javax.swing.JDialog();
        Btm_Registrar = new javax.swing.JButton();
        Txf_Password = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txf_Username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_Imagen = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Cmb_Tipo = new javax.swing.JComboBox<>();
        chat_prueba = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txt_TextChat = new javax.swing.JLabel();
        Txf_TextMsg = new javax.swing.JTextField();
        Btn_SendMsg = new javax.swing.JButton();
        Btn_RegistrarUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Txt_Usuario = new javax.swing.JLabel();
        Txt_Avatar = new javax.swing.JLabel();
        Btn_ChatPrueba = new javax.swing.JButton();
        Btn_CerrarSesion = new javax.swing.JButton();

        JDialog_RegistrarUser.setTitle("Registrar user");
        JDialog_RegistrarUser.setMinimumSize(new java.awt.Dimension(415, 210));
        JDialog_RegistrarUser.setResizable(false);

        Btm_Registrar.setText("Registrar");
        Btm_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btm_RegistrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Contraseña");

        jLabel2.setText("Nombre");

        jLabel4.setText("Avatar");

        Txt_Imagen.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt_Imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txt_ImagenMouseClicked(evt);
            }
        });

        jLabel5.setText("Tipo");

        Cmb_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));

        javax.swing.GroupLayout JDialog_RegistrarUserLayout = new javax.swing.GroupLayout(JDialog_RegistrarUser.getContentPane());
        JDialog_RegistrarUser.getContentPane().setLayout(JDialog_RegistrarUserLayout);
        JDialog_RegistrarUserLayout.setHorizontalGroup(
            JDialog_RegistrarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog_RegistrarUserLayout.createSequentialGroup()
                .addGroup(JDialog_RegistrarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDialog_RegistrarUserLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(JDialog_RegistrarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(JDialog_RegistrarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JDialog_RegistrarUserLayout.createSequentialGroup()
                                .addComponent(Txf_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addGroup(JDialog_RegistrarUserLayout.createSequentialGroup()
                                .addGroup(JDialog_RegistrarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Cmb_Tipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Txf_Password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)))
                        .addComponent(Txt_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JDialog_RegistrarUserLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(Btm_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        JDialog_RegistrarUserLayout.setVerticalGroup(
            JDialog_RegistrarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog_RegistrarUserLayout.createSequentialGroup()
                .addGroup(JDialog_RegistrarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDialog_RegistrarUserLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(JDialog_RegistrarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Txf_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JDialog_RegistrarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Txf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(JDialog_RegistrarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Cmb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JDialog_RegistrarUserLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Txt_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(Btm_Registrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chat_prueba.setMaximumSize(new java.awt.Dimension(542, 300));
        chat_prueba.setMinimumSize(new java.awt.Dimension(542, 300));
        chat_prueba.setSize(new java.awt.Dimension(542, 300));

        jScrollPane1.setViewportView(Txt_TextChat);

        Btn_SendMsg.setText("Enviar");

        javax.swing.GroupLayout chat_pruebaLayout = new javax.swing.GroupLayout(chat_prueba.getContentPane());
        chat_prueba.getContentPane().setLayout(chat_pruebaLayout);
        chat_pruebaLayout.setHorizontalGroup(
            chat_pruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chat_pruebaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(chat_pruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chat_pruebaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Txf_TextMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chat_pruebaLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(Btn_SendMsg)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        chat_pruebaLayout.setVerticalGroup(
            chat_pruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chat_pruebaLayout.createSequentialGroup()
                .addGroup(chat_pruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chat_pruebaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chat_pruebaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Txf_TextMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Btn_SendMsg)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de administración");

        Btn_RegistrarUser.setText("Registrar usuario");
        Btn_RegistrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegistrarUserActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario");

        Txt_Usuario.setText("Usuario");

        Txt_Avatar.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Avatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Btn_ChatPrueba.setText("Chat prueba");
        Btn_ChatPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ChatPruebaActionPerformed(evt);
            }
        });

        Btn_CerrarSesion.setText("Cerrar sesion");
        Btn_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Txt_Usuario)
                .addGap(18, 18, 18)
                .addComponent(Txt_Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_RegistrarUser)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_CerrarSesion)
                            .addComponent(Btn_ChatPrueba))
                        .addGap(11, 11, 11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_RegistrarUser)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_ChatPrueba)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_CerrarSesion))
                    .addComponent(Txt_Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Txt_Usuario)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_RegistrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegistrarUserActionPerformed
        JDialog_RegistrarUser.dispose();
        JDialog_RegistrarUser.setVisible(true);
        Txt_Imagen.setIcon(Utilidades.UrlIcon("https://i.imgur.com/laJbxRN.png", 100, 100));
    }//GEN-LAST:event_Btn_RegistrarUserActionPerformed

    private void Btm_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btm_RegistrarActionPerformed
        Usuario NewUser = new Usuario();
        try {
            NewUser.registrar_user(Txf_Username.getText(), Txf_Password.getText(), Cmb_Tipo.getSelectedIndex(), Txt_Imagen.getIcon());
        } catch (IOException ex) {
            Logger.getLogger(Main_Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "<html><body>Usuario registrado<br>Usuario: <b>" + Txf_Username.getText() + "</b>", "Confirmación registro", JOptionPane.INFORMATION_MESSAGE);
        JDialog_RegistrarUser.setVisible(false);
    }//GEN-LAST:event_Btm_RegistrarActionPerformed

    private void Txt_ImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_ImagenMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("PNG, JPG, JPEG, GIF", "png", "jpg", "jpeg", "gif"));
        fileChooser.setLocation(this.rootPane.getLocationOnScreen());
        fileChooser.setAcceptAllFileFilterUsed(false);
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                File imagen = fileChooser.getSelectedFile();
                BufferedImage imagenbuffer = ImageIO.read(imagen);
                imagenbuffer = Utilidades.resize(imagenbuffer, 100, 100);
                Txt_Imagen.setIcon(new ImageIcon(imagenbuffer));
            } catch (IOException ex) {
                Logger.getLogger(Main_Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Txt_ImagenMouseClicked

    private void Btn_ChatPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ChatPruebaActionPerformed
        //chat_prueba.dispose();
        chat_prueba.setVisible(true);
        Serverchat serverchat = new Serverchat();
        Thread thread = new Thread(serverchat);
        thread.start();
    }//GEN-LAST:event_Btn_ChatPruebaActionPerformed

    private void Btn_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CerrarSesionActionPerformed
        Utilidades.restartApplication();
    }//GEN-LAST:event_Btn_CerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Admin().setVisible(true);
            }
        });
    }

    private static void inicio() {
        Txt_Usuario.setText(Variables.usuario.getUsername());
        Txt_Avatar.setIcon(Utilidades.BlobToImageIcon(Variables.usuario.getAvatar()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btm_Registrar;
    private javax.swing.JButton Btn_CerrarSesion;
    private javax.swing.JButton Btn_ChatPrueba;
    private javax.swing.JButton Btn_RegistrarUser;
    private javax.swing.JButton Btn_SendMsg;
    private javax.swing.JComboBox<String> Cmb_Tipo;
    private javax.swing.JDialog JDialog_RegistrarUser;
    private javax.swing.JTextField Txf_Password;
    private javax.swing.JTextField Txf_TextMsg;
    private javax.swing.JTextField Txf_Username;
    private static javax.swing.JLabel Txt_Avatar;
    private javax.swing.JLabel Txt_Imagen;
    private javax.swing.JLabel Txt_TextChat;
    private static javax.swing.JLabel Txt_Usuario;
    private javax.swing.JFrame chat_prueba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
